// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXdJyJejzfU3vqzuPpcaHJB8ivVqORkXQ',
    appId: '1:422479867383:web:516f24ebb191210c7952f2',
    messagingSenderId: '422479867383',
    projectId: 'careconnect-7dd45',
    authDomain: 'careconnect-7dd45.firebaseapp.com',
    storageBucket: 'careconnect-7dd45.firebasestorage.app',
    measurementId: 'G-8V80M5VQT8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCa4DIeTIFvE4Kc9m9IsFy-ca0ElQJWz_c',
    appId: '1:422479867383:android:99aef4539e61849a7952f2',
    messagingSenderId: '422479867383',
    projectId: 'careconnect-7dd45',
    storageBucket: 'careconnect-7dd45.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCP5UCvxAhXnaqHTgpxga8M80uoKQUd9N8',
    appId: '1:422479867383:ios:ae4b2d1bdbaf5e487952f2',
    messagingSenderId: '422479867383',
    projectId: 'careconnect-7dd45',
    storageBucket: 'careconnect-7dd45.firebasestorage.app',
    iosBundleId: 'com.service.careconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCP5UCvxAhXnaqHTgpxga8M80uoKQUd9N8',
    appId: '1:422479867383:ios:ae4b2d1bdbaf5e487952f2',
    messagingSenderId: '422479867383',
    projectId: 'careconnect-7dd45',
    storageBucket: 'careconnect-7dd45.firebasestorage.app',
    iosBundleId: 'com.service.careconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXdJyJejzfU3vqzuPpcaHJB8ivVqORkXQ',
    appId: '1:422479867383:web:d4d6160672fe181a7952f2',
    messagingSenderId: '422479867383',
    projectId: 'careconnect-7dd45',
    authDomain: 'careconnect-7dd45.firebaseapp.com',
    storageBucket: 'careconnect-7dd45.firebasestorage.app',
    measurementId: 'G-621EH24HD7',
  );

}